language: r
sudo: required
cache: packages
dist: trusty
r:
    - oldrel
    - release
    - devel
r_github_packages:
    - syberia/stagerunner
    - robertzk/testthatsomemore
    - kirillseva/covr
    - robertzk/mungebits

r_binary_packages:
    - roxygen2
    - testthat
    - microbenchmark
    - crayon
    - httr
    - jsonlite
    - whisker
    - shiny
    - devtools

after_success:
  - "Rscript -e 'library(covr);coveralls()'"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/655fbe5e7a5067377f3f
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: IJzwXRM+lT/lL+bNt5mS4QvQ69dDCGVKuoZ+jr6udxqyDejM9lhaw5pl2t43iUIEDvIjDm4eOog+3iiZEbVYdHk6jHKeDyy0eYw2UbplhWpzf/tq9gJX1rSEC6U15MEOtKk+3AomTo2KRX3f0gsE0QdstCPV8UNkr6dbVqZQr/0=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
