language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r testthat microbenchmark"
- "./travis-tool.sh install_github robertzk/stagerunner robertzk/testthatsomemore kirillseva/covr"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: IJzwXRM+lT/lL+bNt5mS4QvQ69dDCGVKuoZ+jr6udxqyDejM9lhaw5pl2t43iUIEDvIjDm4eOog+3iiZEbVYdHk6jHKeDyy0eYw2UbplhWpzf/tq9gJX1rSEC6U15MEOtKk+3AomTo2KRX3f0gsE0QdstCPV8UNkr6dbVqZQr/0=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
sudo: true 
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
